[package]
name = "scrubjay"
version = "0.1.0"
authors = ["jordandanford@gmail.com"]

[[bin]]
path = "src/main.rs"
name = "sj"

[dependencies]
clap = "2.19"
ignore = "0.2"
serde = "1.0"
serde_derive = "1.0"
shellexpand = "1.0"
toml = "0.4"
